# -*- coding: utf-8 -*-
"""Copy of Untitled34.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m26gGPRLsufjjuLWw9y2bMDhDoSKFHzF

# Yana's code
"""

import re
import torch
from transformers import MarianMTModel, MarianTokenizer

device = "cuda" if torch.cuda.is_available() else "cpu"

def clean_armenian(text: str) -> str:
    text = re.sub(r'[♩♪♫♬♭♮♯#]+', '', text)
    lines = [l for l in text.split('\n') if l.strip()]
    return '\n'.join(lines).strip()

# ── Model 1: English → Armenian ───────────────────────────────
print("⏳ Loading English→Armenian model...")
_en_hy_tokenizer = MarianTokenizer.from_pretrained("Helsinki-NLP/opus-mt-en-hy")
_en_hy_model     = MarianMTModel.from_pretrained("Helsinki-NLP/opus-mt-en-hy").to(device)
_en_hy_model.eval()
print("✅ English→Armenian loaded!")

# ── Model 2: Armenian → English ───────────────────────────────
print("⏳ Loading Armenian→English model...")
_hy_en_tokenizer = MarianTokenizer.from_pretrained("Helsinki-NLP/opus-mt-hy-en")
_hy_en_model     = MarianMTModel.from_pretrained("Helsinki-NLP/opus-mt-hy-en").to(device)
_hy_en_model.eval()
print("✅ Armenian→English loaded!")

# ── Psychology glossary ───────────────────────────────────────
GLOSSARY = {
    "anxiety disorder":  "տագնապային խանգարում",
    "panic attack":      "խուճապային գրոհ",
    "suicidal thoughts": "ինքնասպանության մտքեր",
    "suicidal":          "ինքնասպանական",
    "insomnia":          "անքնություն",
    "depression":        "դեպրեսիա",
    "bipolar":           "բիպոլյար",
    "cognitive":         "ճանաչողական",
    "therapy":           "թերապիա",
    "disorder":          "խանգարում",
    "syndrome":          "համախտանիշ",
    "anxiety":           "տագնապ",
    "stress":            "սթրես",
    "trauma":            "տրավմա",
    "mental health":     "հոգեկան առողջություն",
}


def translate_to_armenian(text: str) -> str:
    """English → Armenian using Helsinki opus-mt-en-hy (fallback)."""
    if not text or not text.strip():
        return text
    translated_lines = []
    for line in text.split('\n'):
        if not line.strip():
            translated_lines.append(line)
            continue
        inputs = _en_hy_tokenizer(
            [line],
            return_tensors="pt",
            truncation=True,
            max_length=512,
            padding=True,
        ).to(device)
        with torch.no_grad():
            outputs = _en_hy_model.generate(**inputs, num_beams=4, early_stopping=True)
        translated = _en_hy_tokenizer.decode(outputs[0], skip_special_tokens=True)
        for eng, arm in GLOSSARY.items():
            translated = re.sub(re.escape(eng), arm, translated, flags=re.IGNORECASE)
        translated_lines.append(translated)
    return '\n'.join(translated_lines)


def translate_to_armenian_groq(text: str) -> str:
    """English → Armenian using Groq (primary, high quality)."""
    if not text or not text.strip():
        return text
    try:
        response = groq_client.chat.completions.create(
            model="llama-3.1-8b-instant",
            messages=[
                {"role": "system", "content":
                 "You are a professional English to Armenian translator. "
                 "Translate accurately. Keep technical physics and psychology terms correct. "
                 "Output ONLY the Armenian translation, nothing else."},
                {"role": "user", "content": text}
            ],
            max_tokens=1024,
            temperature=0.1,
        )
        translated = response.choices[0].message.content.strip()
        for eng, arm in GLOSSARY.items():
            translated = re.sub(re.escape(eng), arm, translated, flags=re.IGNORECASE)
        return translated
    except Exception as e:
        print(f"Groq translation failed, falling back to Helsinki: {e}")
        return translate_to_armenian(text)  # ← now this exists


def translate_to_english(text: str) -> str:
    """Armenian → English using Helsinki opus-mt-hy-en."""
    if not text or not text.strip():
        return text
    translated_lines = []
    for line in text.split('\n'):
        if not line.strip():
            translated_lines.append(line)
            continue
        inputs = _hy_en_tokenizer(
            [line],
            return_tensors="pt",
            truncation=True,
            max_length=512,
            padding=True,
        ).to(device)
        with torch.no_grad():
            outputs = _hy_en_model.generate(**inputs, num_beams=4, early_stopping=True)
        translated = _hy_en_tokenizer.decode(outputs[0], skip_special_tokens=True)
        translated_lines.append(translated)
    return '\n'.join(translated_lines)

print("✅ Translation cell ready!")

"""# Lily's code"""

import torch
from torch.utils.data import DataLoader
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import pandas as pd
from sklearn.model_selection import train_test_split
from torch.optim import AdamW
from datasets import Dataset

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("emotion_data.csv")
df = df.dropna(subset=["statement", "status"])
df = df.sample(n=10000, random_state=42)



label_map = {"Normal":0, "Anxiety":1, "Bipolar":2, "Depression":3, "Suicidal":4}
df['label_id'] = df['status'].map(label_map)
df = df.dropna(subset=['label_id'])
df = df.drop(columns=['Unnamed: 0'])
df['label_id'] = df['label_id'].astype(int)
print(df.isna().sum())

print(df.head())
len(df)

import torch
from transformers import AutoModelForSequenceClassification, AutoTokenizer


num_labels = len(label_map)

model_name = "distilbert-base-uncased"

# Define the device for model training
device = torch.device('cpu')
print(f"Using device: {device}")

model = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=num_labels
).to(device)

tokenizer = AutoTokenizer.from_pretrained(model_name)

class MyDataset(torch.utils.data.Dataset):
    def __init__(self, texts, labels):
        self.encodings = tokenizer(texts, truncation=True, padding=True)
        self.labels = labels

    def __getitem__(self, idx):
        item = {k: torch.tensor(v[idx]) for k, v in self.encodings.items()}
        item["labels"] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

dataset = MyDataset(df["statement"].tolist(), df["label_id"].tolist())
loader = DataLoader(dataset, batch_size=16, shuffle=True)

import torch
from torch.utils.data import DataLoader
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch.nn as nn

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

optimizer = torch.optim.Adam(model.parameters(), lr=2e-5)

for epoch in range(3):
    model.train()
    total_loss = 0
    for batch in loader:
        batch = {k: v.to(device) for k, v in batch.items()}

        # Remove 'token_type_ids' if present, as DistilBERT models often don't use them
        if 'token_type_ids' in batch:
            del batch['token_type_ids']

        optimizer.zero_grad()

        outputs = model(**batch)

        loss = outputs.loss
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1}, Loss: {total_loss / len(loader):.4f}")

model.save_pretrained("my_model")
tokenizer.save_pretrained("my_model")

!pip install transformers accelerate bitsandbytes

import torch
import torch.nn.functional as F
from transformers import AutoModelForCausalLM, AutoTokenizer, AutoModelForSequenceClassification # Added AutoModelForSequenceClassification

MODEL_NAME = "microsoft/Phi-3-mini-4k-instruct"

# Renamed Phi-3 tokenizer and model to avoid conflict with classifier
phi3_tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
phi3_model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto",
    torch_dtype="auto"
)

# Load the fine-tuned classification model and its tokenizer
# 'device' variable is available from previous cells.
classifier_tokenizer = AutoTokenizer.from_pretrained("my_model")
classifier_model = AutoModelForSequenceClassification.from_pretrained("my_model").to(device)

# Define id2label mapping (label_map is available from previous cells)
id2label = {v: k for k, v in label_map.items()}

# ===============================
# System Prompt (VERY IMPORTANT)
# ===============================
SYSTEM_PROMPT = """
You are a calm, empathetic mental-health support chatbot.
You ask ONLY ONE short, gentle follow-up question per message.
You do NOT repeat the user's words.
You sound natural, human, and supportive.
You never diagnose or give medical advice.
"""


# ===============================
# Chat function (uses phi3_tokenizer and phi3_model)
# ===============================
def phi3_chat(history):
    messages = [{"role": "system", "content": SYSTEM_PROMPT}] + history

    encoded_inputs = phi3_tokenizer.apply_chat_template(
        messages,
        return_tensors="pt",
        add_generation_prompt=True
    ).to(phi3_model.device)

    output = phi3_model.generate(
        input_ids=encoded_inputs['input_ids'],
        attention_mask=encoded_inputs['attention_mask'],
        max_new_tokens=100,
        temperature=0.7,
        top_p=0.9,
        do_sample=True
    )

    reply = phi3_tokenizer.decode(
        output[0][encoded_inputs['input_ids'].shape[-1]:],
        skip_special_tokens=True
    )

    return reply.strip()

# ===============================
# Classifier function
# ===============================
def detect_state_probs(text):
    classifier_model.eval() # Set model to evaluation mode
    inputs = classifier_tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        padding=True,
        max_length=128
    ).to(device)

    # Remove 'token_type_ids' if present, as DistilBERT models often don't use them
    if 'token_type_ids' in inputs:
        del inputs['token_type_ids']

    with torch.no_grad():
        outputs = classifier_model(**inputs)
        logits = outputs.logits
        probabilities = torch.softmax(logits, dim=1)[0]
    return probabilities

!pip install flask flask-cors pyngrok --quiet

import threading, torch
from flask import Flask, request, jsonify
from flask_cors import CORS
from pyngrok import ngrok, conf

app = Flask(__name__)
CORS(app)
session_probs      = {}
conversation_store = {}  # { session_id: [{role, content}] }

print("SYSTEM_PROMPT:", SYSTEM_PROMPT[:50])
print("id2label:", id2label)

MENTAL_STATE_LABELS_HY = {
    "Normal":     "Նորմալ",
    "Anxiety":    "Տագնապ",
    "Bipolar":    "Բիպոլյար",
    "Depression": "Դեպրեսիա",
    "Suicidal":   "Ինքնասպանական",
}

@app.route('/chat', methods=['POST'])
def chat():
    data     = request.get_json()
    msg      = data.get('message', '').strip()
    history  = data.get('history', [])
    sid      = data.get('session_id', 'default')
    language = data.get('language', 'en')          # ← TRANSLATION
    if not msg:
        return jsonify({'error': 'No message'}), 400

    # Step 1: Armenian input → English so models understand
    english_msg = translate_to_english(msg) if language == 'hy' else msg

    # Step 2: Detect mental state from English message
    probs = detect_state_probs(english_msg)
    session_probs.setdefault(sid, []).append(probs)
    avg          = torch.stack(session_probs[sid]).mean(dim=0)
    mental_state = {id2label[i]: round(p.item()*100, 2) for i, p in enumerate(avg)}

    # Step 3: Save user message to conversation store
    if sid not in conversation_store:
        conversation_store[sid] = []
    conversation_store[sid].append({'role': 'user', 'content': english_msg})

    # Step 4: Phi-3 uses full saved history (not just what Flutter sends)
    reply_en = phi3_chat(conversation_store[sid].copy())

    # Step 5: Save assistant reply to store
    conversation_store[sid].append({'role': 'assistant', 'content': reply_en})

    # Step 6: Translate reply → Armenian if needed
    reply = translate_to_armenian_groq(reply_en) if language == 'hy' else reply_en

    # Step 7: Translate mental state labels → Armenian if needed
    if language == 'hy':
        mental_state = {MENTAL_STATE_LABELS_HY.get(k, k): v for k, v in mental_state.items()}

    return jsonify({'response': reply, 'mental_state': mental_state})


@app.route('/history', methods=['POST'])
def get_history():
    """Return saved conversation for a session."""
    data = request.get_json()
    sid  = data.get('session_id', 'default')
    lang = data.get('language', 'en')
    msgs = conversation_store.get(sid, [])

    if lang == 'hy':
        msgs = [{'role': m['role'],
                 'content': translate_to_armenian_groq(m['content'])}
                for m in msgs]

    return jsonify({'history': msgs})


@app.route('/reset', methods=['POST'])
def reset():
    sid = request.get_json().get('session_id', 'default')
    session_probs.pop(sid, None)
    conversation_store.pop(sid, None)      # ← also clears saved conversation
    return jsonify({'status': 'ok'})


@app.route('/health', methods=['GET'])
def health():
    return jsonify({'status': 'ok'})


ngrok.set_auth_token("YOUR_NGROK_TOKEN_HERE")
url = ngrok.connect(5000)
print(f"\n✅ API Live → {url}\n👉 Paste into ColabAIService.baseUrl\n")
threading.Thread(target=lambda: app.run(port=5000, use_reloader=False)).start()

"""# Codes we can need but they are commented

pip install python-telegram-bot transformers torch
from telegram import Update
from telegram.ext import ApplicationBuilder, MessageHandler, filters, ContextTypes

BOT_TOKEN = "YOUR_BOT_TOKEN_HERE"

user_states = {}  # chat_id → history & probabilities
MAX_TURNS = 5"

async def handle_message(update: Update, context: ContextTypes.DEFAULT_TYPE):
    chat_id = update.effective_chat.id
    text = update.message.text

    if chat_id not in user_states:
        user_states[chat_id] = {
            "history": [],
            "probs": [],
            "turns": 0
        }

    data = user_states[chat_id]

    data["history"].append({"role": "user", "content": text})

    # --- classifier ---
    probs = detect_state_probs(text)
    data["probs"].append(probs)

    # --- chat response ---
    reply = phi3_chat(data["history"])
    data["history"].append({"role": "assistant", "content": reply})

    await update.message.reply_text(reply)

    data["turns"] += 1

    # --- finish conversation ---
    if data["turns"] >= MAX_TURNS:
        final_probs = torch.stack(data["probs"]).mean(dim=0)

        result = "\n🧠 Final mental state estimation:\n"
        for i, p in enumerate(final_probs):
            result += f"{id2label[i]}: {p.item()*100:.2f}%\n"

        await update.message.reply_text(result)
        del user_states[chat_id]"

!pip install nest_asyncio
import nest_asyncio

nest_asyncio.apply()

app = ApplicationBuilder().token(BOT_TOKEN).build()
app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle_message))

print("Bot is running...")
app.run_polling()
"""



'''# ===============================
# MAIN CHAT LOOP
# ===============================
MAX_TURNS = 5
turn = 0

history = []
all_probs = []

print("🟢 Chat started (type 'exit' to stop)\n")

while turn < MAX_TURNS:
    user_input = input("You: ")

    if user_input.lower() == "exit":
        break

    history.append({"role": "user", "content": user_input})

    # --- Classifier (silent) ---
    probs = detect_state_probs(user_input)
    all_probs.append(probs)

    # --- Bot reply ---
    bot_reply = phi3_chat(history)
    print("Bot:", bot_reply)

    history.append({"role": "assistant", "content": bot_reply})

    turn += 1

if all_probs: # Ensure all_probs is not empty before stacking
    final_probs = torch.stack(all_probs).mean(dim=0)

    print("\n🧠 FINAL MENTAL STATE ESTIMATION")
    print("================================")
    for i, p in enumerate(final_probs):
        print(f"{id2label[i]}: {p.item()*100:.2f}%")
    print("================================")
else:
    print("\nNo chat turns completed, no final mental state estimation.")'''

'''# ── Paste this as ONE new cell, after all your model cells ──

!pip install flask flask-cors pyngrok --quiet

import threading, torch
from flask import Flask, request, jsonify
from flask_cors import CORS
from pyngrok import ngrok, conf

app = Flask(__name__)
CORS(app)
session_probs = {}

print("SYSTEM_PROMPT:", SYSTEM_PROMPT[:50])
print("id2label:", id2label)

@app.route('/chat', methods=['POST'])
def chat():
    data = request.get_json()
    msg, history, sid = data.get('message','').strip(), data.get('history',[]), data.get('session_id','default')
    if not msg: return jsonify({'error': 'No message'}), 400

    probs = detect_state_probs(msg)
    session_probs.setdefault(sid, []).append(probs)
    avg = torch.stack(session_probs[sid]).mean(dim=0)
    mental_state = {id2label[i]: round(p.item()*100, 2) for i, p in enumerate(avg)}

    reply = phi3_chat(history)

    return jsonify({'response': reply, 'mental_state': mental_state})

@app.route('/reset', methods=['POST'])
def reset():
    session_probs.pop(request.get_json().get('session_id','default'), None)
    return jsonify({'status': 'ok'})

@app.route('/health', methods=['GET'])
def health():
    return jsonify({'status': 'ok'})


ngrok.set_auth_token("YOUR_NGROK_TOKEN_HERE")
url = ngrok.connect(5000)
print(f"\n✅ API Live → {url}\n👉 Paste into ColabAIService.baseUrl\n")
threading.Thread(target=lambda: app.run(port=5000, use_reloader=False)).start()'''