# -*- coding: utf-8 -*-
"""emodu_edu.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EaymXzLcJ1pLGuLRLZAkhduJk2ya0mWl

# Imports
"""

!pip install faiss-cpu pymupdf python-docx sentence-transformers transformers accelerate groq flask flask-cors pyngrok -q

import numpy as np
import torch
import pandas as pd
import gc
import json
import os
import re
import fitz
import socket
import threading
import time

from docx          import Document as DocxDocument
from functools     import lru_cache
from sentence_transformers import SentenceTransformer
import faiss
from transformers  import AutoTokenizer, AutoModelForSeq2SeqLM, MarianMTModel, MarianTokenizer
from sympy         import symbols, Eq, solve, Float
from groq          import Groq
from flask         import Flask, request, jsonify
from flask_cors    import CORS
from pyngrok       import ngrok, conf

device = "cuda" if torch.cuda.is_available() else "cpu"
torch.set_num_threads(8)
print(f"Using device: {device}")

"""# Yana's translation


"""

def clean_armenian(text: str) -> str:
    """Remove garbage characters that Helsinki model sometimes outputs."""
    text = re.sub(r'[♩♪♫♬♭♮♯#]+', '', text)
    lines = [l for l in text.split('\n') if l.strip()]
    return '\n'.join(lines).strip()

_en_hy_tokenizer = MarianTokenizer.from_pretrained("Helsinki-NLP/opus-mt-en-hy")
_en_hy_model     = MarianMTModel.from_pretrained("Helsinki-NLP/opus-mt-en-hy").to(device)
_en_hy_model.eval()

_hy_en_tokenizer = MarianTokenizer.from_pretrained("Helsinki-NLP/opus-mt-hy-en")
_hy_en_model     = MarianMTModel.from_pretrained("Helsinki-NLP/opus-mt-hy-en").to(device)
_hy_en_model.eval()

#Physics
GLOSSARY = {
    "mass defect":       "զանգվածի դեֆեկտ",
    "atomic number":     "ատոմային թիվ",
    "isotopes":          "իզոտոպներ",
    "kinetic energy":    "կինետիկ էներգիա",
    "potential energy":  "պոտենցիալ էներգիա",
    "acceleration":      "արագացում",
    "velocity":          "արագություն",
    "momentum":          "իմպուլս",
    "wavelength":        "ալիքի երկարություն",
    "frequency":         "հաճախականություն",
    "electric field":    "էլեկտրական դաշտ",
    "magnetic field":    "մագնիսական դաշտ",
    "neutron":           "նեյտրոն",
    "proton":            "պրոտոն",
    "electron":          "էլեկտրոն",
    "force":             "ուժ",
    "energy":            "էներգիա",
    "gravity":           "ձգողականություն",
    "friction":          "շփում",
    "pressure":          "ճնշում",
    "temperature":       "ջերմաստիճան",
    "resistance":        "դիմադրություն",
    "voltage":           "լարում",
    "current":           "հոսանք",
    "nuclear":           "միջուկային",
    "quantum":           "քվանտ",
    "refraction":        "բեկում",
    "reflection":        "անդրադարձում",
    "thermodynamics":    "ջերմادینամիկա",
    "entropy":           "էնտրոպիա",
    "time dilation":     "ժամանակի դանդաղում",
    "binding energy":    "կապի էներգիա",
    "fission":           "տրոհում",
    "fusion":            "միաձուլում",
    "photon":            "ֆոտոն",
    "diffraction":       "դիֆրակցիա",
    "interference":      "ինտերֆերենցիա",
    "capacitor":         "կոնդենսատոր",
    "circuit":           "շղթա",
}


def translate_to_armenian(text: str) -> str:
    """Translate English → Armenian using Helsinki model."""
    if not text or not text.strip():
        return text
    translated_lines = []
    for line in text.split('\n'):
        if not line.strip():
            translated_lines.append(line)
            continue
        inputs = _en_hy_tokenizer(
            [line],
            return_tensors="pt",
            truncation=True,
            max_length=512,
            padding=True,
        ).to(device)
        with torch.no_grad():
            outputs = _en_hy_model.generate(**inputs, num_beams=4, early_stopping=True)
        translated = _en_hy_tokenizer.decode(outputs[0], skip_special_tokens=True)
        translated = clean_armenian(translated)
        translated_lines.append(translated)
    return '\n'.join(translated_lines)


def translate_to_armenian_groq(text: str) -> str:
    """Translate English → Armenian using Groq (much better quality)."""
    if not text or not text.strip():
        return text
    try:
        response = groq_client.chat.completions.create(
            model="llama-3.1-8b-instant",
            messages=[
                {"role": "system", "content":
                 "You are a professional English to Armenian translator. "
                 "Translate the text accurately. "
                 "Keep technical physics and psychology terms correct. "
                 "Output ONLY the Armenian translation, nothing else."},
                {"role": "user", "content": text}
            ],
            max_tokens=512,
            temperature=0.1,
        )
        translated = response.choices[0].message.content.strip()
        for eng, arm in GLOSSARY.items():
            translated = re.sub(re.escape(eng), arm, translated, flags=re.IGNORECASE)
        return translated
    except Exception as e:
        print(f"Groq translation failed, falling back to Helsinki: {e}")
        return translate_to_armenian(text)


def translate_to_english(text: str) -> str:
    """Armenian → English using opus-mt-hy-en."""
    if not text or not text.strip():
        return text
    translated_lines = []
    for line in text.split('\n'):
        if not line.strip():
            translated_lines.append(line)
            continue
        inputs = _hy_en_tokenizer(
            [line],
            return_tensors="pt",
            truncation=True,
            max_length=512,
            padding=True,
        ).to(device)
        with torch.no_grad():
            outputs = _hy_en_model.generate(**inputs, num_beams=4, early_stopping=True)
        translated = _hy_en_tokenizer.decode(outputs[0], skip_special_tokens=True)
        translated_lines.append(translated)
    return '\n'.join(translated_lines)

print("translation models ready")

"""# Models"""

#LaMini-Flan-T5-783M - q&a / explanations

LLM_NAME      = "MBZUAI/LaMini-Flan-T5-783M"
llm_tokenizer = AutoTokenizer.from_pretrained(LLM_NAME)
llm_model     = AutoModelForSeq2SeqLM.from_pretrained(
    LLM_NAME, torch_dtype=torch.float32
).to(device)
llm_model.eval()

#flan-t5-base - flashcards
FC_MODEL_ID  = "google/flan-t5-base"
fc_tokenizer = AutoTokenizer.from_pretrained(FC_MODEL_ID)
fc_model     = AutoModelForSeq2SeqLM.from_pretrained(
    FC_MODEL_ID, torch_dtype=torch.float32
).to(device)
fc_model.eval()

#Groq (llama-3.1-8b-instant) - summarization
GROQ_API_KEY = "YOUR_GROQ_API_KEY"
groq_client  = Groq(api_key=GROQ_API_KEY)

"""Generation helper"""

def llm_generate(question: str, context: str) -> str:
    prompt = (
        f"You are a physics textbook. Answer ONLY using the context below. "
        f"Do not add information not present in the context. "
        f"Be accurate and concise in 2-4 sentences.\n\n"
        f"Context: {context[:800]}\n\n"
        f"Question: {question}\n\n"
        f"Answer:"
    )
    inputs = llm_tokenizer(
        prompt, return_tensors="pt", truncation=True, max_length=512
    ).to(device)
    with torch.no_grad():
        outputs = llm_model.generate(
            **inputs,
            max_new_tokens=150,
            num_beams=8,
            no_repeat_ngram_size=3,
            early_stopping=True,
            pad_token_id=llm_tokenizer.pad_token_id,
        )
    return llm_tokenizer.decode(outputs[0], skip_special_tokens=True).strip()


def fc_generate(prompt: str, max_new_tokens: int = 400) -> str:
    """flan-t5-base — flashcard JSON generation."""
    inputs = fc_tokenizer(
        prompt, return_tensors="pt", truncation=True, max_length=512
    ).to(device)
    with torch.no_grad():
        outputs = fc_model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            num_beams=2,
            no_repeat_ngram_size=3,
            early_stopping=True,
            pad_token_id=fc_tokenizer.pad_token_id,
        )
    return fc_tokenizer.decode(outputs[0], skip_special_tokens=True).strip()

"""# Solving  and explainig

math problem solving
"""

v, v0, a, t, d, m, F, g = symbols('v v0 a t d m F g')
KE, PE, W, P, r, freq, lam, c = symbols('KE PE W P r f lam c')
V, I, R, Q, mc, dT = symbols('V I R Q mc dT')

FORMULAS = {
    "vf":   Eq(v,    v0 + a * t),
    "dist": Eq(d,    v0 * t + Float('0.5') * a * t ** 2),
    "vf2":  Eq(v**2, v0**2 + 2 * a * d),
    "fall": Eq(d,    Float('0.5') * g * t ** 2),
    "F=ma": Eq(F,    m * a),
    "KE":   Eq(KE,   Float('0.5') * m * v ** 2),
    "PE":   Eq(PE,   m * g * d),
    "W":    Eq(W,    F * d),
    "P":    Eq(P,    W / t),
    "wave": Eq(c,    freq * lam),
    "ohm":  Eq(V,    I * R),
    "heat": Eq(Q,    mc * dT),
}

EXTRACT_PATTERNS = {
    "v0":   r"(?:initial(?:ly)?|starts? at|traveling at|moving at)\s+([\d.]+)\s*m/?s",
    "v":    r"(?:final(?:ly)?|reaches?|accelerates? to|slows? to)\s+([\d.]+)\s*m/?s",
    "t":    r"(?:in|takes?|after|for)\s+([\d.]+)\s*(?:s|sec|second)",
    "d":    r"(?:distance|height|cliff|travels?)\s+(?:of\s+)?([\d.]+)\s*m",
    "m":    r"([\d.]+)\s*kg",
    "F":    r"([\d.]+)\s*N\b",
    "a":    r"accelerat\w+\s+(?:at\s+)?([\d.]+)\s*m/?s",
    "freq": r"([\d.]+)\s*Hz",
    "lam":  r"wavelength\s+(?:of\s+)?([\d.]+)",
    "V":    r"([\d.]+)\s*[Vv]olts?",
    "I":    r"([\d.]+)\s*[Aa]mps?",
    "R":    r"([\d.]+)\s*ohms?",
    "mc":   r"specific heat\s+([\d.]+)",
    "dT":   r"temperature change\s+([\d.]+)",
    # ── NEW: generic speed pattern for "constant speed of X m/s" ──
    "speed": r"(?:constant\s+)?speed\s+of\s+([\d.]+)\s*m/?s",
}

SYM_MAP = {
    "v": v, "v0": v0, "a": a, "t": t, "d": d, "m": m, "F": F, "g": g,
    "KE": KE, "PE": PE, "W": W, "P": P, "freq": freq, "lam": lam,
    "c": c, "V": V, "I": I, "R": R, "Q": Q, "mc": mc, "dT": dT,
}


def extract(question):
    vals = {}
    for var, pat in EXTRACT_PATTERNS.items():
        match = re.search(pat, question, re.IGNORECASE)
        if match:
            vals[var] = float(match.group(1))

    # ── FIX: handle "constant speed" → treat as v0=v=speed, a=0 ──
    if "speed" in vals and "v0" not in vals and "v" not in vals:
        vals["v0"] = vals["speed"]
        vals["v"]  = vals["speed"]
        vals["a"]  = 0.0

    return vals


def route(question, vals):
    q   = question.lower()
    has = vals.__contains__

    # ── FIX: constant speed + time → distance (d = v*t) ──
    if any(w in q for w in ["how far", "distance", "travel"]):
        if has("v0") and has("a") and vals.get("a") == 0.0 and has("t"):
            return "dist", d

    if any(w in q for w in ["dropped", "falls", "cliff", "how high"]):
        vals.setdefault("v0", 0.0)
        vals.setdefault("g", 9.8)
        if has("t"): return "fall", d
        if has("d"): return "fall", t

    if "acceleration" in q:
        if has("v0") and has("v") and has("t"): return "vf",   a
        if has("v0") and has("v") and has("d"): return "vf2",  a
        if has("m")  and has("F"):              return "F=ma", a

    if any(w in q for w in ["distance", "how far", "travel"]):
        if has("v0") and has("a") and has("t"): return "dist", d
        if has("v0") and has("v") and has("d"): return "vf2",  d

    if any(w in q for w in ["final velocity", "final speed", "how fast"]):
        if has("v0") and has("a") and has("t"): return "vf",  v
        if has("v0") and has("a") and has("d"): return "vf2", v

    if "force"            in q and has("m") and has("a"):            return "F=ma", F
    if "kinetic energy"   in q and has("m") and has("v"):            return "KE",   KE
    if "potential energy" in q and has("m") and has("d"):
        vals.setdefault("g", 9.8);                                    return "PE",   PE
    if "work"  in q and has("F") and has("d"):                       return "W",    W
    if "power" in q and has("W") and has("t"):                       return "P",    P
    if "wave"  in q and has("freq") and has("lam"):                  return "wave", c
    if any(w in q for w in ["ohm", "voltage", "current"]):
        if has("I") and has("R"): return "ohm", V
        if has("V") and has("R"): return "ohm", I
        if has("V") and has("I"): return "ohm", R
    if "heat" in q and has("mc") and has("dT"):                      return "heat", Q

    return None, None


def solve_physics(question):
    vals     = extract(question)
    key, unk = route(question, vals)
    if key is None:
        return None
    subs = {SYM_MAP[k]: val for k, val in vals.items() if k in SYM_MAP}
    try:
        res  = solve(FORMULAS[key].subs(subs), unk)
        nums = [float(x) for x in res if x.is_real]
        pos  = [x for x in nums if x >= 0]
        ans  = pos[0] if pos else (nums[0] if nums else None)
        if ans is None:
            return None
        return {"answer": ans, "formula": str(FORMULAS[key]), "vals": vals}
    except Exception:
        return None

"""dataset filtre"""

PHYSICS_TOPICS = [
    "General Physics", "Mechanics", "Electromagnetism",
    "Thermodynamics", "Optics", "Modern Physics",
    "Astronomy", "Waves & Sound",
]

EMB_FILE   = "light_embeddings.npy"
TEXT_FILE  = "physics_texts.csv"
INDEX_FILE = "physics_index.faiss"

TOPIC_KEYWORDS = {
    "Mechanics":        ["force", "newton", "mass", "acceleration", "velocity", "momentum", "energy", "work", "power", "gravity", "friction", "torque"],
    "Electromagnetism": ["electric", "magnetic", "charge", "current", "voltage", "resistance", "ohm", "field", "capacitor", "circuit"],
    "Thermodynamics":   ["heat", "temperature", "entropy", "thermodynamic", "gas", "pressure", "carnot", "thermal"],
    "Optics":           ["light", "lens", "mirror", "refraction", "reflection", "diffraction", "interference", "wavelength", "photon"],
    "Modern Physics":   ["quantum", "relativity", "einstein", "atom", "nuclear", "radioactive", "uncertainty", "bohr"],
    "Astronomy":        ["star", "planet", "galaxy", "universe", "solar", "orbit", "black hole", "neutron", "supernova", "astronomy"],
    "Waves & Sound":    ["wave", "sound", "frequency", "amplitude", "resonance", "doppler", "harmonic", "vibration"],
    "General Physics":  ["physics", "law", "principle", "theory", "measurement", "scalar", "vector"],
}


def detect_topic(query: str):
    q      = query.lower()
    scores = {topic: sum(1 for kw in kws if kw in q)
              for topic, kws in TOPIC_KEYWORDS.items()}
    best   = max(scores, key=scores.get)
    return best if scores[best] > 0 else None


def load_and_filter_data():
    df = pd.read_csv("physics_clean_dataset.csv")
    df = df[df["topic"].isin(PHYSICS_TOPICS)].copy()
    df = df.dropna(subset=["text_content"])
    df = df[df["text_content"].str.len() >= 80]
    df = df[df["text_content"].str.len() <= 3000]
    df = df.drop_duplicates(subset="text_content")
    df = (
        df.groupby("topic", group_keys=False)
          .apply(lambda x: x.sample(min(len(x), 800), random_state=42))
          .reset_index(drop=True)
    )
    mmlu = df[df["source"].str.startswith("mmlu")]
    wiki = df[df["source"] == "wikipedia_physics"]
    df   = pd.concat([mmlu, wiki]).reset_index(drop=True)
    print(f"Filtered dataset: {len(df)} rows")
    return df

"""Embeddings and faiss"""

def generate_embeddings():
    if os.path.exists(EMB_FILE) and os.path.exists(TEXT_FILE):
        return np.load(EMB_FILE)
    df        = load_and_filter_data()
    sentences = df["text_content"].tolist()
    em        = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2", device=device)
    embeddings = em.encode(
        sentences, batch_size=128, convert_to_numpy=True,
        normalize_embeddings=True, show_progress_bar=True
    )
    np.save(EMB_FILE, embeddings)
    df[["text_content", "topic"]].to_csv(TEXT_FILE, index=False)
    print(f"Embeddings saved: {embeddings.shape}")
    return embeddings


embeddings_array = generate_embeddings()
emb   = embeddings_array.astype("float32")
index = faiss.IndexFlatIP(emb.shape[1])
index.add(emb)
faiss.write_index(index, INDEX_FILE)

texts_df    = pd.read_csv(TEXT_FILE)
texts       = texts_df["text_content"].tolist()
index       = faiss.read_index(INDEX_FILE)
embed_model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2", device=device)


@lru_cache(maxsize=512)
def retrieve_cached(query: str, k: int = 5):
    q_emb      = embed_model.encode([query], normalize_embeddings=True).astype("float32")
    _, I       = index.search(q_emb, k * 4)
    candidates = [(texts[i], i) for i in I[0]]
    detected   = detect_topic(query)

    if detected and "topic" in texts_df.columns:
        matched   = [t for t, i in candidates if texts_df.iloc[i]["topic"] == detected]
        unmatched = [t for t, i in candidates if texts_df.iloc[i]["topic"] != detected]
        ranked    = (matched + unmatched)[:k]
    else:
        ranked = [t for t, _ in candidates[:k]]
    return tuple(ranked)


def retrieve(query, k=5):
    chunks     = retrieve_cached(query, k)
    chunks     = [c for c in chunks if c and len(c.strip()) > 20]
    links      = [c for c in chunks if " — http" in c]
    texts_only = [c for c in chunks if " — http" not in c]
    return texts_only, links

PHYSICS_FACTS = {
    "newton first law":           "Newton's first law (Law of Inertia): An object at rest stays at rest, and an object in motion stays in motion at constant velocity, unless acted upon by an external force.",
    "newton second law":          "Newton's second law: The acceleration of an object is proportional to the net force and inversely proportional to its mass. Formula: F = ma.",
    "newton third law":           "Newton's third law: For every action there is an equal and opposite reaction.",
    "newton law":                 "Newton's three laws: (1) Inertia — objects stay at rest or in motion unless acted on. (2) F = ma. (3) Every action has an equal and opposite reaction.",
    "hooke law":                  "Hooke's Law: F = -kx, where k is the spring constant and x is displacement.",
    "faraday law":                "Faraday's Law: A changing magnetic flux induces an EMF. Formula: EMF = -dΦ/dt.",
    "faraday law of electromagnetic induction": "Faraday's Law: EMF = -dΦ/dt. Discovered by Michael Faraday in 1831.",
    "thermodynamics first law":   "First law: Energy cannot be created or destroyed. ΔU = Q - W.",
    "thermodynamics second law":  "Second law: Total entropy of an isolated system always increases.",
    "thermodynamics third law":   "Third law: As temperature → 0 K, entropy of a perfect crystal → 0.",
    "ohm law":                    "Ohm's Law: V = IR.",
    "law of gravitation":         "Newton's law of gravitation: F = G(m1×m2)/r².",
    "coulomb law":                "Coulomb's Law: F = kq1q2/r².",
    "conservation of energy":     "Energy cannot be created or destroyed; total energy of an isolated system is constant.",
    "conservation of momentum":   "Total momentum of an isolated system is constant: p = mv.",
    "acceleration":               "Acceleration: a = (v - v0) / t, measured in m/s².",
    "speed of light":             "Speed of light in vacuum: c ≈ 3×10⁸ m/s.",
    "kinetic energy":             "KE = ½mv².",
    "potential energy":           "PE = mgh.",
    "transverse wave":            "Transverse waves: particles oscillate perpendicular to wave travel (e.g. light).",
    "longitudinal wave":          "Longitudinal waves: particles oscillate parallel to wave travel (e.g. sound).",
    "transverse and longitudinal": "Transverse: perpendicular oscillation (light, water). Longitudinal: parallel oscillation (sound).",
    "mass and weight":            "Mass (kg) is constant everywhere. Weight (N) = mg; varies with gravity.",
    "mass weight":                "Mass is constant (kg). Weight = mg varies with location.",
    "constant speed distance":    "For constant speed: distance = speed × time (d = v·t).",
}


def check_facts(question: str):
    q = question.lower().strip()
    for prefix in ["what is the difference between ", "what is ", "what are ",
                   "explain ", "define ", "describe ", "state ", "give ",
                   "what do you mean by ", "tell me about "]:
        q = q.replace(prefix, "")
    q = q.replace("'s", "").replace("'", "").replace("?", "").replace(".", "").strip()
    for key, answer in PHYSICS_FACTS.items():
        if key in q or q in key:
            return answer
    for key, answer in PHYSICS_FACTS.items():
        if all(word in q for word in key.split()):
            return answer
    return None

"""# LLM Generation"""

def llm_generate(question: str, context: str) -> str:
    prompt = (
        f"You are a physics textbook. Answer ONLY using the context below. "
        f"Do not add information not present in the context. "
        f"Be accurate and concise in 2-4 sentences.\n\n"
        f"Context: {context[:800]}\n\n"
        f"Question: {question}\n\n"
        f"Answer:"
    )
    inputs = llm_tokenizer(
        prompt, return_tensors="pt", truncation=True, max_length=512
    ).to(device)
    with torch.no_grad():
        outputs = llm_model.generate(
            **inputs,
            max_new_tokens=150,
            num_beams=8,
            no_repeat_ngram_size=3,
            early_stopping=True,
            pad_token_id=llm_tokenizer.pad_token_id,
        )
    return llm_tokenizer.decode(outputs[0], skip_special_tokens=True).strip()


def groq_answer(question: str, context: str) -> str:
    """Use Groq as a fallback for open-ended Q&A when LaMini might hallucinate."""
    try:
        response = groq_client.chat.completions.create(
            model="llama-3.1-8b-instant",
            messages=[
                {"role": "system", "content":
                 "You are a concise physics tutor. Answer the student's question "
                 "accurately in 2-4 sentences using the context provided. "
                 "If the context is insufficient, use your physics knowledge."},
                {"role": "user", "content":
                 f"Context:\n{context[:1200]}\n\nQuestion: {question}"}
            ],
            max_tokens=300,
            temperature=0.2,
        )
        return response.choices[0].message.content.strip()
    except Exception as e:
        print(f"Groq QA fallback failed: {e}")
        return llm_generate(question, context)


def fc_generate(prompt: str, max_new_tokens: int = 400) -> str:
    """flan-t5-base — flashcard JSON generation."""
    inputs = fc_tokenizer(
        prompt, return_tensors="pt", truncation=True, max_length=512
    ).to(device)
    with torch.no_grad():
        outputs = fc_model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            num_beams=2,
            no_repeat_ngram_size=3,
            early_stopping=True,
            pad_token_id=fc_tokenizer.pad_token_id,
        )
    return fc_tokenizer.decode(outputs[0], skip_special_tokens=True).strip()

"""Answer the question part"""

def answer_question(question: str) -> str:
    result = solve_physics(question)
    if result:
        return (
            f"Answer: {result['answer']:.4f}\n"
            f"Formula : {result['formula']}\n"
            f"Known values: {result['vals']}"
        )
    fact = check_facts(question)
    if fact:
        return fact
    chunks, links = retrieve(question, k=5)
    if not chunks:
        return groq_answer(question, "")
    context  = "\n\n".join(chunks)[:1200]
    response = groq_answer(question, context)
    if links:
        response += "\n\n### Study Resources\n" + "\n".join(f"• {l}" for l in links)
    return response

"""Summarization block"""

def read_document(file_path: str) -> str:
    ext = file_path.lower().split(".")[-1]
    if ext == "pdf":
        doc  = fitz.open(file_path)
        text = "".join(page.get_text() for page in doc)
        doc.close()
        return text.strip()
    elif ext == "docx":
        doc = DocxDocument(file_path)
        return "\n".join(p.text for p in doc.paragraphs if p.text.strip())
    elif ext in ("txt", "md"):
        with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
            return f.read()
    else:
        raise ValueError(f"Unsupported file type: .{ext}")


def summarize_document(file_path: str) -> str:
    text     = read_document(file_path)
    response = groq_client.chat.completions.create(
        model="llama-3.1-8b-instant",
        messages=[{
            "role": "user",
            "content": (
                "Summarize the following text clearly and accurately. "
                "Only use information from the text.\n\n" + text
            ),
        }],
        max_tokens=1024,
    )
    return response.choices[0].message.content

"""Flashcards"""

def generate_flashcards_from_text(text: str, num_cards: int = 5) -> list:
    system_prompt = (
        "You are a flashcard generator. "
        "Given a text, produce EXACTLY a JSON array of flashcard objects. "
        'Each object must have exactly two keys: "question" and "answer". '
        "The question must be a clear, standalone question. "
        "The answer must be concise and direct. "
        "NEVER repeat or include the question text inside the answer field. "
        "Output ONLY the raw JSON array, no explanation, no markdown, no code fences."
    )
    user_prompt = (
        f"Create {num_cards} flashcards from this text:\n\n{text[:2000]}\n\n"
        'Respond with ONLY a JSON array like:\n'
        '[{"question":"What is X?","answer":"X is ..."}]\n'
        "Do NOT put the question inside the answer."
    )
    try:
        response = groq_client.chat.completions.create(
            model="llama-3.1-8b-instant",
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user",   "content": user_prompt},
            ],
            max_tokens=1024,
            temperature=0.3,
        )
        raw = response.choices[0].message.content.strip()
        raw = re.sub(r"```[a-z]*\n?", "", raw).strip()
        start = raw.index("[")
        end   = raw.rindex("]") + 1
        cards = json.loads(raw[start:end])
        clean = []
        for c in cards:
            q = str(c.get("question", "")).strip()
            a = str(c.get("answer",   "")).strip()
            if not q or not a:
                continue
            if a.lower().startswith(q.lower()):
                a = a[len(q):].lstrip(" :.–-")
            clean.append({"question": q, "answer": a})
        return clean if clean else _fallback_cards(text, num_cards)
    except Exception as e:
        print(f"Flashcard Groq error: {e}")
        return _fallback_cards(text, num_cards)


def _fallback_cards(text: str, num_cards: int) -> list:
    sentences = [s.strip() for s in re.split(r"(?<=[.!?])\s+", text) if len(s.strip()) > 20]
    cards = []
    for i in range(0, min(len(sentences) - 1, num_cards * 2), 2):
        cards.append({
            "question": sentences[i],
            "answer":   sentences[i + 1] if i + 1 < len(sentences) else "See summary.",
        })
        if len(cards) >= num_cards:
            break
    return cards or [{"question": "What is this lecture about?", "answer": text[:300]}]

"""# Flask to connect to interface"""

app = Flask(__name__)
CORS(app)


@app.route('/health', methods=['GET'])
def health():
    return jsonify({'status': 'ok'})


@app.route('/reset', methods=['POST'])
def reset():
    return jsonify({'status': 'ok'})


@app.route('/chat', methods=['POST'])
def chat():
    data     = request.get_json()
    msg      = (data or {}).get('message', '').strip()
    language = (data or {}).get('language', 'en')
    if not msg:
        return jsonify({'error': 'No message provided'}), 400
    try:
        english_msg = translate_to_english(msg) if language == 'hy' else msg
        answer = answer_question(english_msg)
        if language == 'hy':
            answer = translate_to_armenian_groq(answer)

    except Exception as e:
        answer = f"Error: {e}"
    return jsonify({'response': answer})


@app.route('/summarize', methods=['POST'])
def summarize():
    language = request.args.get('language', 'en')

    data = request.get_json(silent=True, force=True)
    if data and 'file_path' in data:
        language  = data.get('language', language)
        file_path = data['file_path'].strip()
        try:
            summary = summarize_document(file_path)
            if language == 'hy':
                summary = translate_to_armenian_groq(summary)
            return jsonify({'summary': summary})
        except Exception as e:
            return jsonify({'error': str(e)}), 500

    if 'file' in request.files:
        f         = request.files['file']
        save_path = f"/content/{f.filename}"
        f.save(save_path)
        language  = request.form.get('language', language)
        try:
            summary = summarize_document(save_path)
            if language == 'hy':
                summary = translate_to_armenian_groq(summary)
            return jsonify({'summary': summary})
        except Exception as e:
            return jsonify({'error': str(e)}), 500

    return jsonify({
        'error':          'No file or file_path received',
        'received_json':  request.get_json(silent=True, force=True),
        'received_files': list(request.files.keys()),
        'content_type':   request.content_type,
    }), 400


@app.route('/study', methods=['POST'])
def study():
    data     = request.get_json()
    text     = (data or {}).get('text', '').strip()
    n        = (data or {}).get('num_cards', 5)
    language = (data or {}).get('language', 'en')
    if not text:
        return jsonify({'error': 'No text provided'}), 400
    cards = generate_flashcards_from_text(text, num_cards=n)
    if language == 'hy':
        for card in cards:
            card['question'] = translate_to_armenian_groq(card['question'])
            card['answer']   = translate_to_armenian_groq(card['answer'])
    return jsonify({'flashcards': cards})


@app.route('/flashcards', methods=['POST'])
def flashcards():
    data     = request.get_json()
    text     = (data or {}).get('text', '').strip()
    n        = (data or {}).get('num_cards', 5)
    language = (data or {}).get('language', 'en')
    if not text:
        return jsonify({'error': 'No text provided'}), 400
    cards = generate_flashcards_from_text(text, num_cards=n)
    if language == 'hy':
        for card in cards:
            card['question'] = translate_to_armenian_groq(card['question'])
            card['answer']   = translate_to_armenian_groq(card['answer'])
    return jsonify({'flashcards': cards})

try:
    for tunnel in ngrok.get_tunnels():
        ngrok.disconnect(tunnel.public_url)
except Exception:
    pass

NGROK_AUTH_TOKEN =  "YOUR_NGROK_TOKEN_HERE"
public_url = None

try:
    conf.get_default().auth_token = NGROK_AUTH_TOKEN
    tunnel     = ngrok.connect(5000)
    public_url = str(tunnel).replace("NgrokTunnel: ", "")
    print(f'\nFlutter kApiBase = "{public_url}"')
except Exception as e:
    print(f"ngrok failed: {e}")


def get_local_ip():
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(("8.8.8.8", 80))
        ip = s.getsockname()[0]
        s.close()
        return ip
    except:
        return "YOUR_IP_ADDRESS"



threading.Thread(target=lambda: app.run(host='0.0.0.0', port=5000, use_reloader=False)).start()
while True:
    time.sleep(1)